### ISSUE TITLE
Your HTML file was not started properly 

### ISSUE THREAD

**Issue by nickmachado** [MelonsAway/more-css-practice#1]
https://github.com/MelonsAway/more-css-practice/blob/38dcb1d88d57a834d6c12aacb5e372f976242105/instagram/index.html#L2

your <!DOCTYPE html> needs to be fixed, you missed the "!" that comes before "DOCTYPE".

**Comment by nickmachado** [comment]
Thats it

**Comment by MelonsAway** [comment]
Fixed!

**Comment by zachfedor** [comment]
If it's fixed, you should push it and close the issue :)
